name: "Merge Into Current Branch"
description: "Merge into current branch using git with recursive strategy"
branding:
  icon: "git-merge"
  color: "blue"
inputs:
  from:
    description: "Branch to merge into the current branch"
    required: true
  author:
    description: "Commit author in Git author format"
    default: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
    required: true
  strategy:
    description: "Merge strategy with any strategy options"
    default: "recursive -Xtheirs"
    required: true
  push:
    description: "Push commit to origin?"
    default: "true"
    required: true
runs:
  using: "composite"
  steps:
    - name: Merge ${{ inputs.from }} with ${{ inputs.strategy }} strategy
      shell: bash
      run: |
        git merge ${{ inputs.from }} \
        -s ${{ inputs.strategy }} \
        --author="${{ inputs.author }}" \
        --no-ff
    - name: Push merge commit to origin
      shell: bash
      run: |
        if [ "${{ inputs.push }}" == "true" ]
        then
          git push origin HEAD
        fi
