name: "Test Action"

on:
  push:
    branches:
      - "**"

env:
  source: "tests-source"
  destination: "tests-destination"
  test-key: "${{ format('{0}-{1}', github.run_id, github.run_number) }}"

jobs:
  fixtures:
    runs-on: ubuntu-latest
    outputs:
      destination: "${{ env.destination }}-${{ env.test-key }}"
      source: "${{ env.source }}-${{ env.test-key }}"
    env:
      destination: "${{ env.destination }}-${{ env.test-key }}"
      source: "${{ env.source }}-${{ env.test-key }}"
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - run: "git checkout -b ${{ env.destination }}"
      - run: "git checkout -b ${{ env.source }}"
      - run: "git push origin ${{ env.destination }} ${{ env.source }}"
      - run: "echo ${{ env.test-key }} > example-change.test"
      - run: "git add example-change.test"
      - run: "git commit -m 'chore: Add example file'"
      - run: "git push --set-upstream origin ${{ env.source }}"
  integration-tests:
    runs-on: ubuntu-latest
    needs:
      - fixtures
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "${{ needs.fixtures.outputs.destination }}"
      - uses: ./
        with:
          from: "${{ env.source }}"
          # author: "Alice Tester <alice@example.com>"
          # strategy: "recursive -Xtheirs"
          # push: true
