name: "Test Action"

on:
  push:
    branches:
      - "**"

env:
  source: "${{ format('{0}-{1}-{2}', 'tests-source', github.run_id, github.run_number) }}"
  destination: "${{ format('{0}-{1}-{2}', 'tests-destination', github.run_id, github.run_number) }}"

jobs:
  fixtures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - run: "git checkout -b ${{ env.destination }}"
      - run: "git checkout -b ${{ env.source }}"
      - run: "echo ${{ env.destination }} > example-change.test"
      - run: "git add example-change.test"
      - run: "git commit -m 'chore: Add example file'"
      - run: "git push --set-upstream origin ${{ env.destination }} ${{ env.source }}"
  integration-tests:
    runs-on: ubuntu-latest
    needs:
      - fixtures
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "${{ env.destination }}"
          fetch-depth: 0
      - uses: ./
        with:
          from: "origin/${{ env.source }}"
          # author: "Alice Tester <alice@example.com>"
          # strategy: "recursive -Xtheirs"
          # push: true
